# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20170622_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='team',
        ),
    ]
