# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstore',
            options={'verbose_name': 'teamstore', 'verbose_name_plural': 'teamstores'},
        ),
    ]
