# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamstore', '0002_auto_20170622_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstore',
            name='group_shipping',
            field=models.BooleanField(default=True, verbose_name='group shipping'),
        ),
        migrations.AlterField(
            model_name='teamstore',
            name='team_code',
            field=models.CharField(max_length=25, unique=True, verbose_name='team code'),
        ),
        migrations.AlterField(
            model_name='teamstore',
            name='team_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='team name'),
        ),
    ]
