# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_auto_20170616_1351'),
        ('teamstore', '0003_auto_20170624_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamstore',
            name='shipping_method',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shipping.ShippingMethod', verbose_name='team shipping method'),
        ),
    ]
