# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamstore', '0004_teamstore_shipping_method'),
        ('order', '0017_auto_20170616_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teamstore.TeamStore', verbose_name='team'),
        ),
    ]
